# Generated by Django 5.0.1 on 2024-05-09 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default={})),
                ('status', models.CharField(default='initial', max_length=15)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.numbers')),
            ],
        ),
    ]
