# Generated by Django 5.0.1 on 2024-05-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_calls_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
