# Generated by Django 5.0.1 on 2024-02-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='script',
            name='answer_uz',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='script',
            name='question_ru',
            field=models.TextField(null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='script',
            name='question_uz',
            field=models.TextField(null=True, verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='script',
            name='answer',
            field=models.TextField(verbose_name='Javob'),
        ),
        migrations.AlterField(
            model_name='script',
            name='question',
            field=models.TextField(verbose_name='Savol'),
        ),
    ]
