# Generated by Django 5.0.6 on 2024-05-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recievedfiles',
            name='user',
        ),
    ]
