# Generated by Django 5.0.6 on 2024-05-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0002_remove_recievedfiles_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='to_role',
        ),
    ]
