# Generated by Django 5.0.1 on 2024-02-23 14:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0004_nodegroup_alter_script_folder_id_delete_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NodeGroup',
            new_name='NodeGroups',
        ),
    ]
