# Generated by Django 5.0.1 on 2024-02-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0006_nodegroups_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodegroups',
            name='status',
            field=models.CharField(blank=True, choices=[('Yangi', 'Yangi'), ('Faol', 'Faol'), ('Nofaol', 'Nofaol'), ('Arxiv', 'Arxiv')], max_length=10),
        ),
    ]
